name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # This is correct and the most efficient runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # The MAUI workload install step has been completely REMOVED. It is not needed.

      - name: Publish Blazor WebAssembly app
        # This points to the correct Blazor WASM client project.
        run: dotnet publish DotNetMaui.Web.Client/DotNetMaui.Web.Client.csproj -c Release -o release -p:BaseHref=/DotNetMaui-Portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot